export const FETCH_DATA_DEAL = "FETCH_DATA_DEAL";
export const FETCH_DATA_DEAL_SUCCESS = "FETCH_DATA_DEAL_SUCCESS";
export const FETCH_DATA_DEAL_FALSE = "FETCH_DATA_DEAL_FALSE";
export const SUBMIT_FORM = "SUBMIT_FORM";
export const SUBMIT_FORM_SUCCESS = "SUBMIT_FORM_SUCCESS";
export const SUBMIT_FORM_FALSE = "SUBMIT_FORM_FALSE";
